---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
namespace: default
configMapGenerator:
  - name: kopia
    files:
      - ./config/repository.config
generatorOptions:
  disableNameSuffixHash: true
