---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name node-exporter
spec:
  staticConfigs:
    - targets:
        - pikvm.${SECRET_INTERNAL_DOMAIN}:9100
        - opnsense.${SECRET_INTERNAL_DOMAIN}:9273
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name pikvm
spec:
  staticConfigs:
    - targets: ["pikvm.${SECRET_INTERNAL_DOMAIN}"]
  metricsPath: /api/export/prometheus/metrics
  basicAuth:
    username:
      name: kube-prometheus-stack-secret
      key: PIKVM_USERNAME
    password:
      name: kube-prometheus-stack-secret
      key: PIKVM_PASSWORD
  scheme: HTTPS
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name minio
spec:
  staticConfigs:
    - targets: ["s3.${SECRET_INTERNAL_DOMAIN}"]
  metricsPath: /minio/v2/metrics/cluster
  authorization:
    credentials:
      name: kube-prometheus-stack-secret
      key: MINIO_PROM_TOKEN
  scheme: HTTPS
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
