---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia-charts.yaml
  - authentik-charts.yaml
  - benji-charts.yaml
  - bitnami-charts.yaml
  - cert-manager-webhook-ovh.yaml
  - drone-charts.yaml
  - emxq-charts.yaml
  - gitea-charts.yaml
  - grafana-loki-charts.yaml
  - hajimari-charts.yaml
  - influxdata-charts.yaml
  - infracloudio-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home.yaml
  - k8s-gateway-charts.yaml
  - kasten-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - node-feature-discovery.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - runix-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - twuni-charts.yaml
  - weaveworks-kured-charts.yaml
