---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchorleverage
  namespace: crypto
  labels:
    app.kubernetes.io/instance: anchorleverage
    app.kubernetes.io/name: anchorleverage
  annotations:
    configmap.reloader.stakater.com/reload: "anchorleverage"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: anchorleverage
      app.kubernetes.io/name: anchorleverage
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: anchorleverage
        app.kubernetes.io/name: anchorleverage
    spec:
      containers:
        - image: pirhana/anchorleverage:terraswap-2022042
          #image: luigi311/anchorleverage:20220304
          imagePullPolicy: IfNotPresent
          name: anchorleverage
          env:
            - name: SLEEP_DURATION
              value: "600"
            - name: TIMEOUT_DURATION
              value: "5"
            - name: DEBUG
              value: "False"
            - name: NOTIFY_TELEGRAM
              value: "True"
            - name: PASSWORD
              value: "${SECRET_ANCHOR_PASSWORD}"
            - name: CHAIN_ID
              #value: "bombay-12"
              value: "columbus-5"
            - name: WALLET_MIN_UST_BALANCE
              value: "10"
            - name: WALLET_MAX_UST_BALANCE
              value: "20"
            - name: MAX_SPREAD
              value: "0.01"
            - name: ANCHOR_USAGE_TARGET_PERCENTAGE
              value: "85"
            - name: ANCHOR_USAGE_MIN_PERCENTAGE
              value: "80"
            - name: ANCHOR_USAGE_MAX_PERCENTAGE
              value: "93"
            - name: ANCHOR_ANC_MAX_BALANCE
              value: "20000"
            - name: UST_EARN_TO_BORROW_TARGET_RATIO
              value: "60"
            - name: UST_EARN_TO_BORROW_MIN_RATIO
              value: "5"
            - name: UST_EARN_TO_BORROW_MAX_RATIO
              value: "90"
            - name: DELEVERAGE_BORROW_USAGE_TARGET
              value: "90"
            - name: TERRASWAP_ACTIVE
              value: "false"
          volumeMounts:
            - name: env
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env
          configMap:
            name: anchorleverage
