apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - blackbox-exporter
  - botkube
  - grafana
  - healthchecks
  - kube-prometheus-stack
  #- loki-stack
  - thanos
  - uptime-kuma
