---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homelab-nas-photo-sorter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      music-transcode:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "0 */3 * * *"
        containers:
          app:
            image:
              repository: ghcr.io/auricom/kubectl
              tag: 1.35@sha256:71393dc59f63ac59693178479118fc074f4abf9de2d663fe4f6ab9dcd10e98de
            command:
              - /bin/bash
              - -c
              - |
                #!/bin/bash

                set -o errexit
                set -o nounset

                if [[ -n "$HEALTHCHECKS_ID" ]]; then
                    curl --silent --max-time 10 --retry 5 "https://hc-ping.com/$HEALTHCHECKS_ID/start"
                fi

                cd /app

                /app/photo-sorter.sh

                # Send completion ping to healthchecks
                if [[ -n "$HEALTHCHECKS_ID" ]]; then
                    curl --silent --max-time 10 --retry 5  "https://hc-ping.com/$HEALTHCHECKS_ID"
                fi
            env:
              SORT_SOURCE_DIR: /mnt/vol1/photo/mobile
              SORT_DEST_DIR: /mnt/vol1/photo
            envFrom:
              - secretRef:
                  name: homelab-nas-photo-sorter-secret
    service:
      app:
        controller: *app
        enabled: false
    persistence:
      scripts:
        type: configMap
        name: homelab-nas-photo-sorter-configmap
        defaultMode: 0775 # trunk-ignore(yamllint/octal-values)
        globalMounts:
          - path: /app/photo-sorter.sh
            subPath: script.sh
            readOnly: true
      photo:
        type: nfs
        path: /mnt/vol1/photo
        server: 192.168.9.10
        globalMounts:
          - path: /mnt/vol1/photo
