---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_LB_K8SGATEWAY: 192.168.169.100
  CLUSTER_LB_NGINX: 192.168.169.101
  CLUSTER_LB_SMTP_RELAY: 192.168.169.102
  CLUSTER_LB_UNIFI: 192.168.169.103
  CLUSTER_LB_GITEA: 192.168.169.104
  CLUSTER_LB_QBITTORRENT: 192.168.169.105
  CLUSTER_LB_RESILIOSYNC: 192.168.169.106
  CLUSTER_LB_HASS: 192.168.169.107
  CLUSTER_LB_SYSLOG: 192.168.169.108
  CLUSTER_LB_EMQX: 192.168.169.109
  CLUSTER_LB_TDARR: 192.168.169.110
  LOCAL_LAN: 192.168.8.0/22
  LOCAL_LAN_OPNSENSE: 192.168.8.1
  LOCAL_LAN_TRUENAS: 192.168.9.10
  LOCAL_LAN_TRUENAS_REMOTE: 10.10.0.2
  LOCAL_LAN_COREELEC: 192.168.9.60
  LOCAL_LAN_K3SSERVER: 192.168.9.100
  LOCAL_LAN_K3SWORKER1: 192.168.9.105
  LOCAL_LAN_K3SWORKER2: 192.168.9.106
  LOCAL_LAN_K3SWORKER3: 192.168.9.107
  LOCAL_LAN_OPENMEDIAVAULT: 192.168.9.13
  TIMEZONE: "Etc/UTC"
