---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crunchy-postgres-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes: [ReadWriteMany]
  storageClassName: nfs-csi #csi-driver-nfs
  nfs:
    server: 192.168.9.10
    path: /mnt/vol1/apps/csi-driver-nfs/crunchy-postgres
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - nodiratime
    - rsize=131072
    - wsize=131072
    - nconnect=8
  persistentVolumeReclaimPolicy: Delete
