---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homelab-nas-backup
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      storage:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@daily"
        containers:
          app:
            image:
              repository: ghcr.io/auricom/python
              tag: rolling@sha256:8adb47648d4dc90eba653636dba20182dc3ba7bab084381db0d8a4569092196a
            command:
              - /bin/bash
              - -c
              - |
                #!/bin/bash

                set -o errexit
                set -o nounset

                if [[ -n "$HEALTHCHECKS_ID" ]]; then
                    curl --silent --max-time 10 --retry 5 "https://hc-ping.com/$HEALTHCHECKS_ID/start"
                fi

                python /app/script.py \
                    -H $HOST \
                    -k $API_KEY \
                    -o $BACKUP_LOCATION \
                    --secret-seed --root-keys \
                    --keep 90

                # Send completion ping to healthchecks
                if [[ -n "$HEALTHCHECKS_ID" ]]; then
                    curl --silent --max-time 10 --retry 5  "https://hc-ping.com/$HEALTHCHECKS_ID"
                fi
            env:
              API_KEY:
                secretKeyRef:
                  name: homelab-nas-backup-secret
                  key: STORAGE_TRUENAS_API_KEY
              BACKUP_LOCATION: /mnt/nfs
              HEALTHCHECKS_ID:
                secretKeyRef:
                  name: homelab-nas-backup-secret
                  key: STORAGE_HEALTHCHECKS_ID
              HOST: storage.${SECRET_INTERNAL_DOMAIN}
    service:
      app:
        controller: *app
        enabled: false
    persistence:
      scripts:
        type: configMap
        name: homelab-nas-backup-configmap
        defaultMode: 0775 # trunk-ignore(yamllint/octal-values)
        globalMounts:
          - path: /app/script.py
            subPath: script.py
            readOnly: true
      nfs:
        type: nfs
        path: /mnt/vol1/apps/homelab_backups/truenas/storage.${SECRET_INTERNAL_DOMAIN}
        server: 192.168.9.10
        globalMounts:
          - path: /mnt/nfs
