---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homelab-truenas-backup
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      storage:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@daily"
        containers:
          app:
            image:
              repository: ghcr.io/auricom/kubectl
              tag: 1.35@sha256:cc00ea7635c117da35d496a049e822330ae04e6e5b4152e26d2d5ee179b61b37
            command:
              - /bin/bash
              - -c
              - |
                #!/bin/bash

                set -o errexit
                set -o nounset

                if [[ -n "$HEALTHCHECKS_ID" ]]; then
                    curl --silent --max-time 10 --retry 5 "https://hc-ping.com/$HEALTHCHECKS_ID/start"
                fi

                /app/backup.sh

                # Send completion ping to healthchecks
                if [[ -n "$HEALTHCHECKS_ID" ]]; then
                    curl --silent --max-time 10 --retry 5  "https://hc-ping.com/$HEALTHCHECKS_ID"
                fi
            env:
              API_KEY:
                secretKeyRef:
                  name: homelab-truenas-backup-secret
                  key: STORAGE_TRUENAS_API_KEY
              BACKUP_LOCATION: /mnt/nfs
              HEALTHCHECKS_ID:
                secretKeyRef:
                  name: homelab-truenas-backup-secret
                  key: STORAGE_HEALTHCHECKS_ID
              HOSTNAME: storage.${SECRET_INTERNAL_DOMAIN}
              SORT_DEST_DIR: /mnt/vol1/photo
    service:
      app:
        controller: *app
        enabled: false
    persistence:
      scripts:
        type: configMap
        name: homelab-truenas-backup-configmap
        defaultMode: 0775 # trunk-ignore(yamllint/octal-values)
        globalMounts:
          - path: /app/backup.sh
            subPath: script.sh
            readOnly: true
      nfs:
        type: nfs
        path: /mnt/vol1/apps/homelab_backups/truenas/storage.${SECRET_INTERNAL_DOMAIN}
        server: 192.168.9.10
        globalMounts:
          - path: /mnt/nfs
