---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre-web-automated
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: volsync
      namespace: volsync
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/default/calibre/calibre-web-automated
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      GATUS_SUBDOMAIN: calibre
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre-downloader
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/default/calibre/calibre-downloader
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: books
      VOLSYNC_CAPACITY: 1Gi
