---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: default
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: rook-ceph-block
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: https://truenas.${SECRET_DOMAIN}:51515
      serverName: postgres-v4
      s3Credentials:
        accessKeyId:
          name: postgres-minio
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio
          key: MINIO_SECRET_KEY
  # bootstrap:
  #   recovery:
  #     source: postgres
  # externalClusters:
  #   - name: postgres
  #     barmanObjectStore:
  #       destinationPath: s3://postgresql/
  #       endpointURL: https://truenas.${SECRET_DOMAIN}:51515
  #       s3Credentials:
  #         accessKeyId:
  #           name: postgres-minio
  #           key: MINIO_ACCESS_KEY
  #         secretAccessKey:
  #           name: postgres-minio
  #           key: MINIO_SECRET_KEY
  #       wal:
  #         maxParallel: 8
