---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: influxdata-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.influxdata.com/
  timeout: 3m
