---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helm-release.yaml
  - ./secret.sops.yaml
  - ./volume.yaml
patchesStrategicMerge:
  - ./patches/env.yaml
  - ./patches/postgres.yaml
