---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./atuin/ks.yaml
  - ./authelia/ks.yaml
  - ./bazarr/ks.yaml
  - ./bookstack/ks.yaml
  - ./calibre/ks.yaml
  # - ./clusterpolicies/ks.yaml
  - ./esphome/ks.yaml
  - ./exercisediary/ks.yaml
  - ./filebrowser/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./flood/ks.yaml
  - ./freshrss/ks.yaml
  - ./garage/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homebox/ks.yaml
  - ./homelab/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./joplin/ks.yaml
  - ./komf/ks.yaml
  - ./komga/ks.yaml
  - ./libmedium/ks.yaml
  - ./lidarr/ks.yaml
  - ./linkding/ks.yaml
  - ./lldap/ks.yaml
  - ./lms/ks.yaml
  # - ./lychee/ks.yaml
  - ./mesh-organizer/ks.yaml
  - ./minio/ks.yaml
  - ./navidrome/ks.yaml
  - ./opengist/ks.yaml
  - ./outline/ks.yaml
  - ./paperless/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-archive/ks.yaml
  - ./readeck/ks.yaml
  - ./recyclarr/ks.yaml
  - ./redlib/ks.yaml
  - ./renamarr/ks.yaml
  - ./resilio-sync/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sharry/ks.yaml
  - ./sonarr/ks.yaml
  - ./spoolman/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./tandoor/ks.yaml
  - ./tdarr/ks.yaml
  - ./unifi/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./vikunja/ks.yaml
  - ./webhook/ks.yaml
  - ./zigbee2mqtt/ks.yaml
