apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - external-snapshotter
  - kube-prometheus-stack
  - node-feature-discovery
  - rook-ceph
  - system-upgrade-controller
