---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - coredens-nodecache
  - descheduler
  # - goldilocks
  - intel-gpu-exporter
  - intel-gpu-plugin
  - kyverno
  - metrics-server
  - node-feature-discovery
  - rbac
  - reloader
  - system-upgrade
  - vpa
