---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: tdarr
    app.kubernetes.io/name: tdarr
  name: tdarr-server
  namespace: media
spec:
  ports:
    - name: server
      port: 8266
      protocol: TCP
      targetPort: 8266
  selector:
    app.kubernetes.io/instance: tdarr
    app.kubernetes.io/name: tdarr
  type: LoadBalancer
  externalIPs:
    - ${CLUSTER_LB_TDARR}
  externalTrafficPolicy: Local
