---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
patchesStrategicMerge:
  - ./patches/postgres.yaml
configMapGenerator:
  - name: pushover-notifier-ankr-queries-configmap
    files:
      - ./config/config.yaml
      - ./config/script.py
generatorOptions:
  disableNameSuffixHash: true
