---
- name: jail-prepare | {{ outside_item.item }} | create .ssh directory
  ansible.builtin.shell:
    cmd: iocage exec {{ outside_item.item }} 'mkdir -p /root/.ssh; echo "" > /root/.ssh/authorized_keys; chmod 700 /root/.ssh; chmod 600 /root/.ssh/authorized_keys'
  become: true

- name: jail-prepare | {{ outside_item.item }} | deploy ssh keys
  ansible.builtin.shell:
    cmd: iocage exec {{ outside_item.item }} 'echo "{{ item }}" >> /root/.ssh/authorized_keys'
  loop: "{{ public_ssh_keys }}"
  become: true

- name: jail-prepare | {{ outside_item.item }} | activate sshd
  ansible.builtin.shell:
    cmd: iocage exec {{ outside_item.item }} 'sysrc sshd_enable="YES"'
  become: true

- name: jail-prepare | {{ outside_item.item }} | sshd permit root login
  ansible.builtin.shell:
    cmd: iocage exec {{ outside_item.item }} 'echo "PermitRootLogin yes" >> /etc/ssh/sshd_config'
  become: true

- name: jail-prepare | {{ outside_item.item }} | start sshd
  ansible.builtin.shell:
    cmd: iocage exec {{ outside_item.item }} 'service sshd start'
  become: true

- name: jail-prepare | {{ outside_item.item }} | install packages
  ansible.builtin.shell:
    cmd: iocage exec {{ outside_item.item }} 'pkg install -y python39 bash; ln -s /usr/local/bin/bash /bin/bash'
  become: true
