---
- name: jails | check if jail exist
  ansible.builtin.shell:
    cmd: iocage list | grep {{ item }}
  loop: "{{ groups['truenas-jails'] }}"
  register: jails_check
  changed_when: false
  failed_when: jails_check.rc != 0 and jails_check.rc != 1

- name: jails | is iocage fetch required
  ansible.builtin.set_fact:
    jail_missing: true
  loop: "{{ jails_check.results }}"
  when: item.rc == 1

- block:
    - name: jails | get current FreeBSD release
      ansible.builtin.shell:
        cmd: freebsd-version -k
      register: release
      failed_when: release.rc != 0

    - name: jails | fetch iocage template {{ release.stdout }}
      ansible.builtin.shell:
        cmd: iocage fetch -r {{ release.stdout }}
      become: true

    - name: jails | create jail
      ansible.builtin.shell:
        cmd: iocage create -r {{ release.stdout }} -n {{ item.item }} dhcp=on boot=on
      loop: "{{ jails_check.results }}"
      when: item.rc == 1
      become: true
  when: jail_missing

- name: jails | init jails
  ansible.builtin.include_tasks: init.yml
  loop: "{{ jails_check.results }}"
  loop_control:
    loop_var: outside_item
  when: outside_item.rc == 1
