---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./deploy/cert-manager-webhook-ovh
      version: 0.3.0
      sourceRef:
        kind: GitRepository
        name: cert-manager-webhook-ovh
        namespace: flux-system
      interval: 1440m
  values:
    groupName: "${SECRET_DOMAIN}"
