---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-attic-appiserver
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/default/attic/apiserver
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: attic-apiserver
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-attic-garbage-collector
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-attic-appiserver
  path: ./kubernetes/apps/default/attic/garbage-collector
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: attic-garbage-collector
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
