apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- crypto
  - data
  - development
  - home-automation
  - kasten-io
  - media
  - monitoring
  - networking
  - secret-reflector
