---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wallabag
  namespace: default
spec:
  values:
    env:
      SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
      SYMFONY__ENV__DATABASE_HOST: ${POSTGRES_HOST}
      SYMFONY__ENV__DATABASE_PORT: ${POSTGRES_PORT}
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__REDIS_HOST: redis.default.svc.cluster.local.
      SYMFONY__ENV__DOMAIN_NAME: https://wallabag.${SECRET_CLUSTER_DOMAIN}
      SYMFONY__ENV__SERVER_NAME: Wallabag
      SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
      SYMFONY__ENV__FOSUSER_CONFIRMATION: "false"
      POPULATE_DATABASE: "false"
