---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CILIUM_BGP_SVC_RANGE: 192.168.169.0/24
  CILIUM_POD_CIDR: 10.69.0.0/16
  CLUSTER_LB_K8SGATEWAY: 192.168.169.100
  CLUSTER_LB_NGINX: 192.168.169.101
  CLUSTER_LB_SMTP_RELAY: 192.168.169.102
  CLUSTER_LB_UNIFI: 192.168.169.103
  CLUSTER_LB_GITEA: 192.168.169.104
  CLUSTER_LB_QBITTORRENT: 192.168.169.105
  CLUSTER_LB_RESILIOSYNC_CLAUDE: 192.168.169.106
  CLUSTER_LB_HASS: 192.168.169.107
  CLUSTER_LB_VECTOR: 192.168.169.108
  CLUSTER_LB_EMQX: 192.168.169.109
  CLUSTER_LB_JELLYFIN: 192.168.169.110
  CLUSTER_LB_RESILIOSYNC_HELENE: 192.168.169.111
  CLUSTER_LB_BORGSERVER: 192.168.169.112
  LOCAL_LAN: 192.168.8.0/22
  LOCAL_LAN_OPNSENSE: 192.168.8.1
  LOCAL_LAN_TRUENAS: 192.168.9.10
  LOCAL_LAN_TRUENAS_REMOTE: 10.10.0.2
  TIMEZONE: "Europe/Paris"
  POSTGRES_HOST: "postgres-rw.default.svc.cluster.local."
  POSTGRES_PORT: "5432"
