---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia.yaml
  - buffering-large.yaml
  - buffering-medium.yaml
  - buffering-small.yaml
  - rfc1918.yaml
  - redirect-path.yaml
  - forward-auth.yaml
