---
#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#globalcluster-variables
#

# Use a specific version of k3s
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_release_version: "v1.24.2+k3s1"

# -- Install using hard links rather than symbolic links.
# ...if you are using the system-upgrade-controller you will need to
# use hard links rather than symbolic links as the controller will
# not be able to follow symbolic links.
k3s_install_hard_links: true

# -- Escalate user privileges for all tasks.
k3s_become: true

# -- Enable debugging
k3s_debug: false

# -- Enabled embedded etcd
# k3s_etcd_datastore: false

# -- Enable for single or even number of masters
k3s_use_unsupported_config: false

# -- /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_templates:
  - "calico/calico-installation.yaml.j2"
  - "calico/calico-bgpconfiguration.yaml.j2"
  - "calico/calico-bgppeer.yaml.j2"

# -- /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_urls:
  - url: https://docs.projectcalico.org/archive/v3.23/manifests/tigera-operator.yaml
    filename: tigera-operator.yaml

# -- /etc/rancher/k3s/registries.yaml
# k3s_registries:
#   mirrors:
#     "docker.io":
#       endpoint:
#         - "https://mirror.{{ SECRET_PRIVATE_DOMAIN }}"
#     "*":
#       endpoint:
#         - "https://mirror.{{ SECRET_PRIVATE_DOMAIN }}"
#   config:
#     "https://registry.{{ SECRET_PRIVATE_DOMAIN }}":
#       auth:
#         username: "{{ SECRET_NEXUS_USERNAME }}"
#         password: "{{ SECRET_NEXUS_PASSWORD }}"

timezone: Europe/Paris

public_ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL+GMHgvbtf6f7xUMAQR+vZFfD/mIIfIDNX5iP8tDRXZ claude@claude-thinkpad-fedora"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINo7E0oAOzaq0XvUHkWvZSC8u1XxX8dDCq3bSyK2BCen claude@claude-fixe-fedora"

packages:
  - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - dnf-automatic
  - dnf-utils
  - fish
  - hdparm
  - htop
  - intel-gpu-tools
  - ipvsadm
  # TODO(ansible): Might be required for newer Intel CPU generations
  # https://ask.fedoraproject.org/t/intel-graphics-best-practices-and-settings-for-hardware-acceleration/21119
  # - intel-media-driver
  # - mesa-dri-drivers
  # - libva-intel-driver
  # - libva-intel-hybrid-driver
  # - libva-utils
  # - libva-vdpau-driver
  # - libvdpau-va-gl
  - lm_sensors
  - nano
  - nvme-cli
  - socat
  - cockpit-pcp

k3s_registration_address: 192.168.9.100
