apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rook/rook/v1.9.7/deploy/examples/monitoring/rbac.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.9.7/deploy/examples/monitoring/localrules.yaml
patches:
  - path: modify-rules-patch.yaml
    target:
      group: monitoring.coreos.com
      version: v1
      kind: PrometheusRule
      name: prometheus-ceph-rules
      namespace: rook-ceph
