---
dns_server: 192.168.8.1
# Enable to skip apt upgrade
skip_upgrade_packages: false
# Enable to skip removing crufty packages
skip_remove_packages: false

# Timezone for the servers
timezone: "${TIMEZONE}"

# # Set custom ntp servers
# ntp_servers:
#   primary:
#   - "time.cloudflare.com"
#   - "time.google.com"
#   fallback:
#   - "0.us.pool.ntp.org"
#   - "1.us.pool.ntp.org"
#   - "2.us.pool.ntp.org"
#   - "3.us.pool.ntp.org"

# Additional ssh public keys to add to the nodes
ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL+GMHgvbtf6f7xUMAQR+vZFfD/mIIfIDNX5iP8tDRXZ claude@claude-thinkpad-fedora"
