---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-nodecache-primary
  namespace: default
data:
  Corefile: |
    cluster.local:53 {
        errors
        cache {
          success 9984 30
          denial 9984 5
          prefetch 3 60s 15%
        }
        reload
        loop
        bind 169.254.20.10 # Set your cluster dns to this
        nodecache skipteardown
        template IN AAAA {
          rcode NOERROR
        }
        forward . 10.96.0.10 { # Kube-DNS IP
          force_tcp
        }
        prometheus :9253
        health 169.254.20.10:8080
        }
    in-addr.arpa:53 {
        errors
        cache 120
        reload
        loop
        bind 169.254.20.10
        nodecache skipteardown
        template IN AAAA {
          rcode NOERROR
        }
        forward . /etc/resolv.conf {
          force_tcp
        }
        prometheus :9253
        }
    .:53 {
        errors
        cache {
          success 9984 86400
          denial 9984 300
          prefetch 3 60s 15%
        }
        reload
        loop
        bind 169.254.20.10
        nodecache skipteardown
        template IN AAAA {
          rcode NOERROR
        }
        forward . /etc/resolv.conf {
          force_tcp
        }
        prometheus :9253
        }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-nodecache-secondary
  namespace: default
data:
  Corefile: |
    cluster.local:53 {
        errors
        cache {
          success 9984 30
          denial 9984 5
          prefetch 3 60s 15%
        }
        reload
        loop
        bind 169.254.20.10 # Set your cluster dns to this
        template IN AAAA {
          rcode NOERROR
        }
        forward . 10.96.0.10 { # Kube-DNS IP
          force_tcp
        }
        prometheus :9254
        health 169.254.20.10:8082
        }
    in-addr.arpa:53 {
        errors
        cache 120
        reload
        loop
        bind 169.254.20.10
        template IN AAAA {
          rcode NOERROR
        }
        forward . /etc/resolv.conf {
          force_tcp
        }
        prometheus :9254
        }
    .:53 {
        errors
        cache {
          success 9984 86400
          denial 9984 300
          prefetch 3 60s 15%
        }
        reload
        loop
        bind 169.254.20.10
        template IN AAAA {
          rcode NOERROR
        }
        forward . /etc/resolv.conf {
          force_tcp
        }
        prometheus :9254
        }
