apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - bazarr
  - flood
  - jellyfin
  - jobs
  - lidarr
  - lychee
  - navidrome
  - prowlarr
  - pyload
  - qbittorrent
  - radarr
  - readarr
  - sabnzbd
  - sonarr
  - tdarr
  # - travelstories
  - trash-updater
  - volumes
