---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./configmap.yaml
  - ./microservices
  - ./machine-learning
  - ./secret.sops.yaml
  - ./redis
  - ./server
  - ./typesense
  - ./volume.yaml
  - ./web
