---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - cert-manager-webhook-ovh.yaml
  - cert-manager-webhook-ovh-helm-release.yaml
  - letsencrypt-production.yaml
  - letsencrypt-staging.yaml
  - prometheus-rule.yaml
  - secret.sops.yaml
