apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
patchesStrategicMerge:
  - ./patches/postgres.yaml
configMapGenerator:
  - name: invidious-server
    files:
      - ./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
