apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - data.yaml
  - default.yaml
  - development.yaml
  - falco-system.yaml
  - flux-system.yaml
  - home-automation.yaml
  - kasten-io.yaml
  - kube-system.yaml
  - media.yaml
  - monitoring.yaml
  - networking.yaml
  - rook-ceph.yaml
  - system-upgrade.yaml
